version = 1

[[analyzers]]
name = "sql"
enabled = true

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/KhanShaad12/test3"
  dependencies_vendored = true

[[analyzers]]
name = "docker"
enabled = true